### ISSUE TITLE
Template review feedback

### ISSUE THREAD

**Issue by praveena-pappu** [BytesMatter/google-tag-manager-template#1]
Thanks for submitting a template to the gallery, there were a few issues in your template that needed to be resolved ahead of approving the template for the gallery.

1) We are unable to import the template file to test the template. We see "Error importing template" error. 
![Screenshot 2021-10-01 10 49 51 AM](https://user-images.githubusercontent.com/53495700/135665070-d48efaf3-aceb-41b7-bfcd-392125d86c72.png)

**Comment by bytesmatterdave** [comment]
Hi @praveena-pappu,

Thanks for checking. Apologies, I had made a change to the description that meant the template could not be parsed correctly.  That is fixed. Have manually imported the file to confirm.  Metadata updated to point to the latest update. 
Also added a README file

**Comment by bytesmatterdave** [comment]
Closing this now as it has been addressed
